config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path_names => { :sign_in => 'login', :sign_out => 'logout' }
  devise_scope :user do
    get '/login', to: 'devise/sessions#new'
    get '/logout', to: 'devise/sessions#destroy'
  end

  get 'dashboard' => 'dashboard#index', :as => 'user_root'
  get 'dashboard' => 'dashboard#index', :as => 'dashboard'

  resources :users
  resources :outbound_messages

  match '/webhook/delivery', to: 'webhook_event_requests#delivery_outbound_messages', via: [:get]
  match '/webhook/bounce',   to: 'webhook_event_requests#bounce_outbound_messages',   via: [:get]
  match '/webhook/opens',    to: 'webhook_event_requests#open_outbound_messages',     via: [:get]

  resources :webhook_event_requests do
    post 'delivery', on: :collection
    post 'bounce', on: :collection
    post 'opens', on: :collection
  end

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/outbound_message.rb
class OutboundMessage < ApplicationRecord
  attr_accessor :message

  validates_presence_of :message_id

  def self.import_outbound_message(message)
    msg = OutboundMessage.where(message_id: message["MessageID"]).take

    unless msg
      begin
        outbound_message = OutboundMessage.new
        outbound_message.tag = message["Tag"] rescue ''
        outbound_message.message_id = message["MessageID"] rescue nil
        outbound_message.to = message["To"] rescue []
        outbound_message.cc = message["Cc"] rescue []
        outbound_message.bcc = message["Bcc"] rescue []
        outbound_message.recipients = message["Recipients"] rescue []
        outbound_message.received_at = message["ReceivedAt"] rescue nil
        outbound_message.from = message["From"] rescue ''
        outbound_message.subject = message["Subject"] rescue ''
        outbound_message.attachments = message["Attachments"] rescue []
        outbound_message.status = message["Status"] rescue ''
        outbound_message.track_opens = message["TrackOpens"] rescue nil
        outbound_message.track_links = message["TrackLinks"] rescue ''

        if outbound_message.save
          puts "Imported MessageID: #{outbound_message.message_id}"
        end
      rescue Exception => e
        puts "#{e.message} \n\n #{e.backtrace.inspect}"
        ErrorMailer.notify_sysadmin('Importing outbound messages from postmark error', e.message, e.backtrace).deliver
      end
    end
  end

  def self.query_postmark_outbound_messages(date_request, offset=0)
    return [] if date_request.blank?
    messages = `curl "https://api.postmarkapp.com/messages/outbound?count=500&offset=#{offset}&todate=#{date_request}&fromdate=#{date_request}" \
                -X GET -H "Accept: application/json" \
                -H "X-Postmark-Server-Token: #{ENV["POSTMARK_API_KEY"]}"`

    messages_to_json = self.parse_messages_to_json(messages)
  end

  def self.parse_messages_to_json(messages)
    return {} if messages.blank?
    parsed_messages = JSON.parse(messages)
  end

  # Curl Postmark API to get the 1st 500 records (Postmark has max 500 records per request)
  def self.get_totalcount_messages_days_ago(date_request)
    messages = query_postmark_outbound_messages(date_request)
    return messages["TotalCount"]
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/webhook_event_request.rb
class WebhookEventRequest < ApplicationRecord
  validates_presence_of :payload
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  layout :choose_layout

  private

  def choose_layout
    devise_controller? ? 'landing' : 'application'
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @title = "Welcome to JL Archive Email"
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title = "Welcome to Jobline"
  end
end

app/controllers/outbound_messages_controller.rb
class OutboundMessagesController < ApplicationController
  before_action :authenticate_user!

  def index
    @messages = OutboundMessage.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end
end

app/controllers/webhook_event_requests_controller.rb
class WebhookEventRequestsController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :destroy]
  before_action :set_webhook_event_request, only: [:show, :destroy]
  protect_from_forgery except: [:delivery, :bounce, :opens]

  # Pagination will be implemented next
  def index
    @title = "Webhook Event Requests"
    @webhook_event_requests = WebhookEventRequest.all
  end

  def show
    @title = "Webhook Event Requests Show"
    # We have an ID alerady from before_action => @webhook_event_request
  end

  def destroy
    @webhook_event_request.destroy
    respond_to do |format|
      format.html { redirect_to webhook_event_requests_url }
      format.json { head :no_content }
    end
  end

  def delivery
    request.body.rewind
    @webhook_event_request = WebhookEventRequest.new(payload: request.body.read, webhook_type: 'delivery')
    @title = "Webhook Delivery"

    if @webhook_event_request.save
      render json: @webhook_event_request, status: :created
    else
      render json: @webhook_event_request.errors, status: :unprocessable_entity
    end
  end

  def bounce
    request.body.rewind
    @webhook_event_request = WebhookEventRequest.new(payload: request.body.read, webhook_type: 'bounce')
    @title = "Webhook Bounce"

    if @webhook_event_request.save
      render json: @webhook_event_request, status: :created
    else
      render json: @webhook_event_request.errors, status: :unprocessable_entity
    end
  end

  def opens
    request.body.rewind
    @webhook_event_request = WebhookEventRequest.new(payload: request.body.read, webhook_type: 'opens')
    @title = "Webhook Opens"

    if @webhook_event_request.save
      render json: @webhook_event_request, status: :created
    else
      render json: @webhook_event_request.errors, status: :unprocessable_entity
    end
  end

  def delivery_outbound_messages
    @delivery_outbound_messages = WebhookEventRequest.where(webhook_type: 'delivery').all
  end

  def bounce_outbound_messages
    @bounce_outbound_messages = WebhookEventRequest.where(webhook_type: 'bounce').all
  end

  def open_outbound_messages
    @open_outbound_messages = WebhookEventRequest.where(webhook_type: 'opens').all
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_webhook_event_request
    @webhook_event_request = WebhookEventRequest.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/outbound_messages_helper.rb
module OutboundMessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/webhook_event_requests_helper.rb
module WebhookEventRequestsHelper
end

app/views/dashboard/index.html.erb
<h1>Jobline Archive Emails</h1>
<h2>We will do a test demo and archive our Email Messages from Postmark</h2>
<p>
  Today is <b><%= Date.today.strftime("%d %b %Y") %></b>, you want to <%= link_to 'Sign out', logout_path %>?
</p>

<ul>
  <li><%= link_to 'Go to User list', users_path %></li>
  <li><%= link_to 'View Outbound Messages', outbound_messages_path %></li>
</ul>

<h4>Postmark Outbouned Webhooks</h4>
<ul>
  <li><%= link_to 'Outbound Webhooks', webhook_event_requests_path %></li>
  <li><%= link_to 'Delivery webhook', webhook_delivery_path %></li>
  <li><%= link_to 'Bounce webhook', webhook_bounce_path %></li>
  <li><%= link_to 'Opens webhook', webhook_opens_path %></li>
</ul>

app/views/home/index.html.erb
<h1>Hi there! Welcome to <u>Jobline Archive Email</u></h1>

<h2>This is a test application</h2>

<p>
  Today is <b><%= Date.today.strftime("%d %B %Y") %></b>, please <%= link_to 'Sign in', login_path %>!
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "Jobline Archive Email - Application" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title || "Jobline Archive Email - Home" %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,400,500,700">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/outbound_messages/index.html.erb
You want to <%= link_to '["Sign out"]', logout_path %> ?
<br />

<ul class="list">
  <li><%= link_to '{Dashboard}', dashboard_path %></li>
  <li><%= link_to '{Outbound Messages}', outbound_messages_path %></li>
  <li><%= link_to '{Users}', users_path %></li>
</ul>

<ul class="list">
  <li><%= link_to '{Outbound Webhooks}', webhook_event_requests_path %></li>
  <li><%= link_to '{Delivery webhook}', webhook_delivery_path %></li>
  <li><%= link_to '{Bounce webhook}', webhook_bounce_path %></li>
  <li><%= link_to '{Opens webhook}', webhook_opens_path %></li>
</ul>

<h1>Outbound Messages</h1>

<table>
  <thead>
    <tr>
      <th>Tag</th>
      <th>MessageID</th>
      <th>ReceivedAt</th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |msg| %>
      <tr>
        <td><%= msg.tag %></td>
        <td><%= msg.message_id %></td>
        <td><%= msg.received_at.strftime("%m %B %y - %l:%M %p") %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/index.html.erb
You want to <%= link_to '["Sign out"]', logout_path %> ?
<br />

<ul class="list">
  <li><%= link_to '{Dashboard}', dashboard_path %></li>
  <li><%= link_to '{Outbound Messages}', webhook_event_requests_path %></li>
  <li><%= link_to '{Users}', users_path %></li>
</ul>

<ul class="list">
  <li><%= link_to '{Outbound Webhooks}', webhook_event_requests_path %></li>
  <li><%= link_to '{Delivery webhook}', webhook_event_requests_path %></li>
  <li><%= link_to '{Bounce webhook}', webhook_event_requests_path %></li>
  <li><%= link_to '{Opens webhook}', webhook_event_requests_path %></li>
</ul>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/webhook_event_requests/bounce_outbound_messages.html.erb
You want to <%= link_to '["Sign out"]', logout_path %> ?
<br />

<ul class="list">
  <li><%= link_to '{Dashboard}', dashboard_path %></li>
  <li><%= link_to '{Outbound Messages}', webhook_event_requests_path %></li>
  <li><%= link_to '{Users}', users_path %></li>
</ul>

<ul class="list">
  <li><%= link_to '{Outbound Webhooks}', webhook_event_requests_path %></li>
  <li><%= link_to '{Delivery webhook}', webhook_delivery_path %></li>
  <li><%= link_to '{Bounce webhook}', webhook_bounce_path %></li>
  <li><%= link_to '{Opens webhook}', webhook_opens_path %></li>
</ul>

<h1>Outbound Messages - Bounce</h1>

<table>
  <thead>
    <tr>
      <th>Payload</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @bounce_outbound_messages.blank? %>
      <tr>
        <td>-</td>
        <<td>-</td>
        <td>-</td>
      </tr>
    <% else %>
      <% @bounce_outbound_messages.each do |bounce_outbound_message| %>
        <tr>
          <td><%= open_outbound_message.payload %></td>
          <td><%= link_to 'Show', bounce_outbound_message %></td>
          <td><%= link_to 'Destroy', bounce_outbound_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/webhook_event_requests/delivery_outbound_messages.html.erb
You want to <%= link_to '["Sign out"]', logout_path %> ?
<br />

<ul class="list">
  <li><%= link_to '{Dashboard}', dashboard_path %></li>
  <li><%= link_to '{Outbound Messages}', webhook_event_requests_path %></li>
  <li><%= link_to '{Users}', users_path %></li>
</ul>

<ul class="list">
  <li><%= link_to '{Outbound Webhooks}', webhook_event_requests_path %></li>
  <li><%= link_to '{Delivery webhook}', webhook_delivery_path %></li>
  <li><%= link_to '{Bounce webhook}', webhook_bounce_path %></li>
  <li><%= link_to '{Opens webhook}', webhook_opens_path %></li>
</ul>

<h1>Outbound Messages - Delivered</h1>

<table>
  <thead>
    <tr>
      <th>Payload</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @delivery_outbound_messages.blank? %>
      <tr>
        <td>-</td>
        <<td>-</td>
        <td>-</td>
      </tr>
    <% else %>
      <% @delivery_outbound_messages.each do |delivery_outbound_message| %>
        <tr>
          <td><%= open_outbound_message.payload %></td>
          <td><%= link_to 'Show', delivery_outbound_message %></td>
          <td><%= link_to 'Destroy', delivery_outbound_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/webhook_event_requests/index.html.erb
You want to <%= link_to '["Sign out"]', logout_path %> ?
<br />

<ul class="list">
  <li><%= link_to '{Dashboard}', dashboard_path %></li>
  <li><%= link_to '{Outbound Messages}', outbound_messages_path %></li>
  <li><%= link_to '{Users}', users_path %></li>
</ul>

<ul class="list">
  <li><%= link_to '{Outbound Webhooks}', webhook_event_requests_path %></li>
  <li><%= link_to '{Delivery webhook}', webhook_delivery_path %></li>
  <li><%= link_to '{Bounce webhook}', webhook_bounce_path %></li>
  <li><%= link_to '{Opens webhook}', webhook_opens_path %></li>
</ul>

<h1>Webhook Event Requests</h1>

<table>
  <thead>
    <tr>
      <th>Payload</th>
      <th>Webhook Type</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @webhook_event_requests.each do |webhook_event_request| %>
      <tr>
        <td><%= webhook_event_request.payload %></td>
        <td><%= webhook_event_request.webhook_type %></td>
        <td><%= link_to 'Show', webhook_event_request %></td>
        <td><%= link_to 'Destroy', webhook_event_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/webhook_event_requests/notify_sysadmin.html.erb
<tr>
  <td>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:550px;">
      <tr>
        <td valign="top" style="padding:20px;padding-top:13px;">
          <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
              <td align="center" valign="top" style="border-bottom:1px solid #E5E5E5;padding-bottom:15px;">
                <span style="color:#427DDD;font-size:20px;font-weight:normal;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;">
                  <%= @msg %>
                </span>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>

  </td>
</tr>
<tr>
  <td>
    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width:550px;">
      <tr>
        <td valign="top">
          <table border="0" cellpadding="0" cellspacing="0" width="100%">
            <tr>
              <td style="padding:20px;padding-top:0px;padding-bottom:40px;">
                <pre style="border:1px solid #F2F2F2;padding:10px;color:#FC6258;font-size:11px;border-radius:3px;width:510px;overflow:scroll;">
                  <% if @backtrace.respond_to?(:each) %>
                    <%- @backtrace.each do |line| %>
                      <%= line[(line.index('/lib/') || 0), line.size] %>
                    <% end %>
                  <% end %>
                </pre>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </td>
</tr>

app/views/webhook_event_requests/notify_sysadmin.text.erb
<%= raw @msg %>

<% if @backtrace.respond_to?(:each) %>
  <%- @backtrace.each do |line| %>
    <%= line %>
  <% end %>
<% end %>

app/views/webhook_event_requests/open_outbound_messages.html.erb
You want to <%= link_to '["Sign out"]', logout_path %> ?
<br />

<ul class="list">
  <li><%= link_to '{Dashboard}', dashboard_path %></li>
  <li><%= link_to '{Outbound Messages}', webhook_event_requests_path %></li>
  <li><%= link_to '{Users}', users_path %></li>
</ul>

<ul class="list">
  <li><%= link_to '{Outbound Webhooks}', webhook_event_requests_path %></li>
  <li><%= link_to '{Delivery webhook}', webhook_delivery_path %></li>
  <li><%= link_to '{Bounce webhook}', webhook_bounce_path %></li>
  <li><%= link_to '{Opens webhook}', webhook_opens_path %></li>
</ul>

<h1>Outbound Messages - Opens</h1>

<table>
  <thead>
    <tr>
      <th>Payload</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% if @open_outbound_messages.blank? %>
      <tr>
        <td>-</td>
        <<td>-</td>
        <td>-</td>
      </tr>
    <% else %>
      <% @open_outbound_messages.each do |open_outbound_message| %>
        <tr>
          <td><%= open_outbound_message.payload %></td>
          <td><%= link_to 'Show', open_outbound_message %></td>
          <td><%= link_to 'Destroy', open_outbound_message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

app/views/webhook_event_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payload:</strong>
  <%= @webhook_event_request.payload %>
</p>

<p>
  <strong>Type:</strong>
  <%= @webhook_event_request.webhook_type %>
</p>

<%= link_to 'Back', webhook_event_requests_path %>